Repository MicrosoftDocs/sql-docs, pull requests merged in 2018-06, with the labels that each got.

#706 Update datediff-transact-sql.md
  docs/t-sql/functions/datediff-transact-sql.md
Labels: do-not-merge

#707 Update: Adding bit link
  docs/t-sql/data-types/numeric-types.md
Labels: do-not-merge

#705 Update datediff-big-transact-sql.md
  docs/t-sql/functions/datediff-big-transact-sql.md
Labels: Change sent to author, ready-to-merge

#627 Remove redundant import
  docs/advanced-analytics/tutorials/use-python-revoscalepy-to-create-model.md
Labels: Change sent to author, ready-to-merge

#708 Add space between sentences
  docs/t-sql/xml/insert-xml-dml.md
Labels: Change sent to author, ready-to-merge

#712 Update app-name-transact-sql.md
  docs/t-sql/functions/app-name-transact-sql.md
Labels: Change sent to author, ready-to-merge

#714 Update examples-using-path-mode.md
  docs/relational-databases/xml/examples-using-path-mode.md
Labels: Change sent to author, ready-to-merge

#722 Update dbts-transact-sql.md
  docs/t-sql/functions/dbts-transact-sql.md
Labels: Change sent to author, ready-to-merge

#723 Update decompress-transact-sql.md
  docs/t-sql/functions/decompress-transact-sql.md
Labels: Change sent to author, ready-to-merge

#725 Update decryptbyasymkey-transact-sql.md
  docs/t-sql/functions/decryptbyasymkey-transact-sql.md
Labels: Change sent to author, ready-to-merge

#726 Update decryptbycert-transact-sql.md
  docs/t-sql/functions/decryptbycert-transact-sql.md
Labels: Change sent to author, ready-to-merge

#727 Update decryptbykeyautoasymkey-transact-sql.md
  docs/t-sql/functions/decryptbykeyautoasymkey-transact-sql.md
Labels: Change sent to author, ready-to-merge

#728 Update decryptbykey-transact-sql.md
  docs/t-sql/functions/decryptbykey-transact-sql.md
Labels: Change sent to author, ready-to-merge

#738 Fix part-of-speech agreement in ACID definition
  docs/relational-databases/blob/remote-blob-store-rbs-sql-server.md
Labels: Change sent to author, ready-to-merge

#740 Reword contradicting and confusing restrictions
  docs/relational-databases/databases/revert-a-database-to-a-database-snapshot.md
Labels: Change sent to author, ready-to-merge

#757 Corrected backup directory name in command description
  docs/linux/tutorial-restore-backup-in-sql-server-container.md
Labels: Change sent to author, do-not-merge

#710 Update datefromparts-transact-sql.md
  docs/t-sql/functions/datefromparts-transact-sql.md
Labels: Change sent to author, ready-to-merge

#709 Update datefirst-transact-sql.md
  docs/t-sql/functions/datefirst-transact-sql.md
Labels: Change sent to author, ready-to-merge

#711 Update datename-transact-sql.md
  docs/t-sql/functions/datename-transact-sql.md
Labels: Change sent to author, do-not-merge, ready-to-merge

#713 Update collation-functions-tertiary-weights-transact-sql.md
  docs/t-sql/functions/collation-functions-tertiary-weights-transact-sql.md
Labels: Change sent to author, ready-to-merge

#715 Update datepart-transact-sql.md
  docs/t-sql/functions/datepart-transact-sql.md
Labels: Change sent to author, do-not-merge

#716 Update datetime2fromparts-transact-sql.md
  docs/t-sql/functions/datetime2fromparts-transact-sql.md
Labels: Change sent to author, ready-to-merge

#717 Update datetimefromparts-transact-sql.md
  docs/t-sql/functions/datetimefromparts-transact-sql.md
Labels: Change sent to author, ready-to-merge

#719 Update day-transact-sql.md
  docs/t-sql/functions/day-transact-sql.md
Labels: Change sent to author, ready-to-merge

#720 Update db-id-transact-sql.md
  docs/t-sql/functions/db-id-transact-sql.md
Labels: Change sent to author, ready-to-merge

#734 Explain trick behind using 3 separate EXEC calls
  docs/relational-databases/tables/manage-retention-of-historical-data-in-system-versioned-temporal-tables.md
Labels: Change sent to author, ready-to-merge

#733 Update decryptbykeyautocert-transact-sql.md
  docs/t-sql/functions/decryptbykeyautocert-transact-sql.md
Labels: Change sent to author, ready-to-merge

#735 Update decryptbypassphrase-transact-sql.md
  docs/t-sql/functions/decryptbypassphrase-transact-sql.md
Labels: Change sent to author, ready-to-merge

#736 Update degrees-transact-sql.md
  docs/t-sql/functions/degrees-transact-sql.md
Labels: Change sent to author, ready-to-merge

#756 Update sqldev-operationalize-the-model.md
  docs/advanced-analytics/tutorials/sqldev-operationalize-the-model.md
Labels: Change sent to author, ready-to-merge

#754 Update error-message-transact-sql.md
  docs/t-sql/functions/error-message-transact-sql.md
Labels: Change sent to author, ready-to-merge

#737 Update dense-rank-transact-sql.md
  docs/t-sql/functions/dense-rank-transact-sql.md
Labels: Change sent to author, ready-to-merge

#721 Update db-name-transact-sql.md
  docs/t-sql/functions/db-name-transact-sql.md
Labels: Change sent to author, ready-to-merge

#742 Update encryptbyasymkey-transact-sql.md
  docs/t-sql/functions/encryptbyasymkey-transact-sql.md
Labels: Change sent to author, ready-to-merge

#762 Fixed case of `Definition` -> `definition`
  docs/relational-databases/system-catalog-views/sys-default-constraints-transact-sql.md
Labels: do-not-merge

#753 Update register-a-service-principal-name-spn-for-a-report-server.md
  docs/reporting-services/report-server/register-a-service-principal-name-spn-for-a-report-server.md
Labels: Change sent to author, ready-to-merge

#730 Update decryptbykeyautoasymkey-transact-sql.md
  docs/t-sql/functions/decryptbykeyautoasymkey-transact-sql.md
Labels: Change sent to author, do-not-merge

#731 Update datediff examples
  docs/t-sql/functions/datediff-transact-sql.md
Labels: Change sent to author, ready-to-merge

#732 Update datediff-big examples
  docs/t-sql/functions/datediff-big-transact-sql.md
Labels: Change sent to author, ready-to-merge

#745 Update error-line-transact-sql.md
  docs/t-sql/functions/error-line-transact-sql.md
Labels: Change sent to author, ready-to-merge

#755 Update error-number-transact-sql.md
  docs/t-sql/functions/error-number-transact-sql.md
Labels: Change sent to author, ready-to-merge

#760 Update error-procedure-transact-sql.md
  docs/t-sql/functions/error-procedure-transact-sql.md
Labels: Change sent to author, ready-to-merge

#761 Update error-severity-transact-sql.md
  docs/t-sql/functions/error-severity-transact-sql.md
Labels: Change sent to author, ready-to-merge

#743 Update eomonth-transact-sql.md
  docs/t-sql/functions/eomonth-transact-sql.md
Labels: ready-to-merge

#750 Minor typo
  docs/t-sql/functions/datepart-transact-sql.md
Labels: Change sent to author, do-not-merge

#758 Update decimal-and-numeric-transact-sql.md
  docs/t-sql/data-types/decimal-and-numeric-transact-sql.md
Labels: Change sent to author, ready-to-merge

#748 Fix typo
  docs/relational-databases/databases/attach-a-database.md
Labels: Change sent to author, do-not-merge

#763 Fixes SSMS Heading inside of the Note above
  docs/ssms/download-sql-server-management-studio-ssms.md
Labels: Change sent to author, ready-to-merge

#776 Update to TDE EKM AKV Setup Documentation
  docs/relational-databases/security/encryption/setup-steps-for-extensible-key-management-using-the-azure-key-vault.md
Labels: Change sent to author, do-not-merge

#777 fix: md extension on azure absolute link
  docs/integration-services/lift-shift/ssis-azure-lift-shift-ssis-packages-overview.md
  docs/integration-services/load-data-to-sql-data-warehouse.md
Labels: Change sent to author, ready-to-merge, sql-data-warehouse

#779 fix: Absolute like refs that are relative
  docs/database-engine/configure-windows/external-scripts-enabled-server-configuration-option.md
  docs/troubleshooters/replication/troubleshoot-tran-repl-errors.md
Labels: Change sent to author, ready-to-merge

#783 Update deploy-integration-services-ssis-projects-and-packages.md
  docs/integration-services/packages/deploy-integration-services-ssis-projects-and-packages.md
Labels: Change sent to author, ready-to-merge

#785 Fix Typo: You see see how JSON...
  docs/relational-databases/json/json-data-sql-server.md
Labels: Change sent to author, ready-to-merge

#786 Typo Fix
  docs/linux/sql-server-linux-active-directory-authentication.md
Labels: Change sent to author, do-not-merge

#784 fix a markdown
  docs/advanced-analytics/TOC.md
Labels: Change sent to author, do-not-merge

#718 Update datetimeoffsetfromparts-transact-sql.md
  docs/t-sql/functions/datetimeoffsetfromparts-transact-sql.md
Labels: Change sent to author, do-not-merge

#799 Removed a repeated sentence
  docs/reporting-services/report-builder/rendering-to-html-report-builder-and-ssrs.md
Labels: Change sent to author, do-not-merge

#801 Rename to /IACCEPTPYTHONLICENSETERMS
  docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md
Labels: Change sent to author, ready-to-merge

#752 Add info about automatic serial redo
  docs/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability.md
Labels: Change sent to author, do-not-merge

#811 Update db-id-transact-sql.md
  docs/t-sql/functions/db-id-transact-sql.md
Labels: Change sent to author, ready-to-merge

#809 Fixed syntax typo
  docs/t-sql/functions/last-value-transact-sql.md
Labels: Change sent to author, ready-to-merge

#808 Add ASSEMBLY as possible class/class_desc
  docs/relational-databases/system-catalog-views/sys-crypt-properties-transact-sql.md
Labels: Change sent to author, ready-to-merge

#807 Updated UNMASK and ALTER ANY MASK with SQL DB
  docs/relational-databases/security/permissions-database-engine.md
Labels: Change sent to author, ready-to-merge

#805 TOP 10 PERCENT disconnect between code and text
  docs/t-sql/queries/top-transact-sql.md
Labels: Change sent to author, ready-to-merge

#798 Update varp-transact-sql.md
  docs/t-sql/functions/varp-transact-sql.md
Labels: Change sent to author, ready-to-merge

#797 Update avg-transact-sql.md
  docs/t-sql/functions/avg-transact-sql.md
Labels: Change sent to author, ready-to-merge

#793 Update stdevp-transact-sql.md
  docs/t-sql/functions/stdevp-transact-sql.md
Labels: Change sent to author, ready-to-merge

#792 Update sum-transact-sql.md
  docs/t-sql/functions/sum-transact-sql.md
Labels: Change sent to author, ready-to-merge

#790 Update var-transact-sql.md
  docs/t-sql/functions/var-transact-sql.md
Labels: Change sent to author, ready-to-merge

#781 Fix typo
  docs/t-sql/statements/alter-database-transact-sql-compatibility-level.md
Labels: Change sent to author, ready-to-merge

#775 Update datetimeoffsetfromparts-transact-sql.md
  docs/t-sql/functions/datetimeoffsetfromparts-transact-sql.md
Labels: Change sent to author, ready-to-merge

#749 Update bulk-insert-transact-sql.md
  docs/t-sql/statements/bulk-insert-transact-sql.md
Labels: Change sent to author, ready-to-merge

#759 Nonsensical sentence fix for JSON documentation
  docs/relational-databases/json/json-data-sql-server.md
Labels: Change sent to author, ready-to-merge

#804 Fixed spacing issues
  docs/relational-databases/system-stored-procedures/sp-add-schedule-transact-sql.md
Labels: Change sent to author, ready-to-merge

#806 Fixed spacing issue
  docs/relational-databases/system-stored-procedures/sp-add-jobserver-transact-sql.md
Labels: Change sent to author, ready-to-merge

#810 Update lesson-1-2
  docs/integration-services/lesson-1-2-adding-and-configuring-a-flat-file-connection-manager.md
Labels: Change sent to author, ready-to-merge

#747 Update sys-dm-os-memory-brokers-transact-sql.md
  docs/relational-databases/system-dynamic-management-views/sys-dm-os-memory-brokers-transact-sql.md
Labels: Change sent to author, ready-to-merge

#815 Update 1-6
  docs/integration-services/lesson-1-6-adding-and-configuring-the-lookup-transformations.md
Labels: Change sent to author, ready-to-merge

#816 Spelling correction
  docs/relational-databases/blob/remote-blob-store-rbs-sql-server.md
Labels: Change sent to author, ready-to-merge

#767 Added missing instance name in example
  docs/database-engine/configure-windows/logging-in-to-sql-server.md
Labels: Change sent to author, ready-to-merge

#782 Fix typo
  docs/database-engine/configure-windows/start-stop-pause-resume-restart-sql-server-services.md
Labels: Change sent to author, ready-to-merge

#802 more concise, increased clarity
  docs/relational-databases/backup-restore/back-up-and-restore-of-sql-server-databases.md
Labels: Change sent to author, ready-to-merge

#803 grammar improvement
  docs/sql-server/editions-and-components-of-sql-server-2017.md
Labels: Change sent to author, ready-to-merge

#822 Making two audit DMVs applicable to SQL DB/DW
  docs/relational-databases/system-dynamic-management-views/sys-dm-audit-actions-transact-sql.md
  docs/relational-databases/system-dynamic-management-views/sys-dm-audit-class-type-map-transact-sql.md
Labels: Change sent to author, do-not-merge

#828 Words were mixed up hyphens instead of underscores
  docs/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server.md
Labels: Change sent to author, ready-to-merge
