Repository MicrosoftDocs/sql-docs, pull requests merged in 2018-02, with the labels that each got.

#394 Added explanation of what causes this and how to avoid it
  docs/database-engine/configure-windows/optimize-for-ad-hoc-workloads-server-configuration-option.md
Labels: Change sent to author, ready-to-merge

#409 Update clr-enabled-server-configuration-option.md
  docs/database-engine/configure-windows/clr-enabled-server-configuration-option.md
Labels: Change sent to author, ready-to-merge

#372 Update language-reference.md
  docs/t-sql/language-reference.md
Labels: Change sent to author, do-not-merge

#405 Add DBCC CHECKIDENT RESEED example when a table is empty
  docs/t-sql/database-console-commands/dbcc-checkident-transact-sql.md
Labels: Change sent to author, do-not-merge

#411 The session is not ended - the batch is
  docs/t-sql/language-elements/throw-transact-sql.md
Labels: Change sent to author, ready-to-merge

#413 Typo in get-started-with-this-simple-example-of-the-import-and-export-wizard.md
  docs/integration-services/import-export-data/get-started-with-this-simple-example-of-the-import-and-export-wizard.md
Labels: Change sent to author, ready-to-merge

#414 Typo in lesson-6-4-deploying-the-lesson-6-package.md
  docs/integration-services/lesson-6-4-deploying-the-lesson-6-package.md
Labels: Change sent to author, ready-to-merge

#415 minor typo fix
  docs/ssdt/download-sql-server-data-tools-ssdt.md
Labels: Change sent to author, do-not-merge

#418 Corrected sqlcmd syntax
  docs/relational-databases/databases/rebuild-system-databases.md
Labels: Change sent to author, do-not-merge

#420 Update sys-dm-exec-describe-first-result-set-transact-sql.md
  docs/relational-databases/system-dynamic-management-views/sys-dm-exec-describe-first-result-set-transact-sql.md
Labels: Change sent to author, do-not-merge

#402 Fixed link.
  docs/reporting-services/report-data/xml-connection-type-ssrs.md
Labels: Change sent to author, do-not-merge

#422 Updated Remarks section
  docs/relational-databases/system-dynamic-management-views/sys-dm-exec-sessions-transact-sql.md
Labels: Change sent to author, do-not-merge

#406 Update dbcc-dropcleanbuffers-transact-sql.md
  docs/t-sql/database-console-commands/dbcc-dropcleanbuffers-transact-sql.md
Labels: Change sent to author, do-not-merge

#424 USE AdventureWorks20012 -> USE AdventureWorks2012
  docs/ssms/tutorials/lesson-3-2-create-custom-templates.md
Labels: Change sent to author, ready-to-merge

#425 right-click the AdventureWorks2012 database
  docs/ssms/tutorials/lesson-3-2-create-custom-templates.md
Labels: Change sent to author, ready-to-merge

#426 Remove extraneous **
  docs/ssms/tutorials/lesson-3-2-create-custom-templates.md
Labels: Change sent to author, ready-to-merge

#421 Changed videos on JSON page
  docs/relational-databases/json/json-data-sql-server.md
Labels: Change sent to author, ready-to-merge

#427 Fix: endate -> enddate.
  docs/t-sql/functions/datediff-transact-sql.md
Labels: Change sent to author, ready-to-merge

#416 Update sql-server-linux-setup-tools.md
  docs/linux/sql-server-linux-setup-tools.md
Labels: Change sent to author, do-not-merge

#404 Update sql-server-linux-security-get-started.md
  docs/linux/sql-server-linux-security-get-started.md
Labels: Change sent to author, ready-to-merge

#428 Update default value for ALLOW_CONNECTIONS
  docs/t-sql/statements/alter-database-azure-sql-database.md
Labels: Change sent to author, ready-to-merge, sql-database

#419 Add Sequel to the list of ORMs
  docs/connect/sql-connection-libraries.md
Labels: Change sent to author, ready-to-merge

#417 Fixed download icon
  docs/sql-server/editions-and-components-of-sql-server-2016.md
  docs/sql-server/editions-and-components-of-sql-server-2017.md
Labels: Change sent to author, do-not-merge

#430 Revert "Add Sequel to the list of ORMs"
  docs/connect/sql-connection-libraries.md
Labels: Change sent to author, do-not-merge

#431 fix return data type
  docs/t-sql/functions/date-and-time-data-types-and-functions-transact-sql.md
Labels: Change sent to author, ready-to-merge

#432 Clarified limitation about dropping under load
  docs/t-sql/statements/drop-database-transact-sql.md
Labels: Change sent to author, do-not-merge

#433 fixed broken sentence and capitalization in note
  docs/t-sql/statements/set-xact-abort-transact-sql.md
Labels: Change sent to author, ready-to-merge

#434 Duplicate Link
  docs/relational-databases/security/securing-sql-server.md
Labels: Change sent to author, ready-to-merge

#435 @newname parameter must be a one-part name
  docs/relational-databases/stored-procedures/rename-a-stored-procedure.md
Labels: Change sent to author, ready-to-merge
