Repository MicrosoftDocs/sql-docs, pull requests merged in 2018-08, with the labels that each got.

#889 Swap titles to match examples
  docs/relational-databases/security/encryption/encrypt-a-column-of-data.md
Labels: ready-to-merge

#890 very minor grammar fix
  docs/t-sql/statements/set-implicit-transactions-transact-sql.md
Labels: ready-to-merge

#887 Added formatting to headers
  docs/relational-databases/triggers/ddl-triggers.md
Labels: Change sent to author, ready-to-merge

#868 Add commands to add UPN to keytab for AD Auth on Linux
  docs/linux/sql-server-linux-active-directory-authentication.md
Labels: Change sent to author, ready-to-merge

#885 Update columnstore-indexes-overview.md
  docs/relational-databases/indexes/columnstore-indexes-overview.md
Labels: Change sent to author, ready-to-merge

#886 Update piecemeal-restores-sql-server.md
  docs/relational-databases/backup-restore/piecemeal-restores-sql-server.md
Labels: Change sent to author, ready-to-merge

#882 Fixed capitalization for .NET
  docs/ssms/download-sql-server-management-studio-ssms.md
Labels: Change sent to author, ready-to-merge

#891 add space between Express and LocalDB
  docs/tools/sqllocaldb-utility.md
Labels: Change sent to author, ready-to-merge

#894 Add Block Monitor Thread
  docs/relational-databases/replication/administration/enhance-transactional-replication-performance.md
Labels: Change sent to author, do-not-merge

#893 Update best-practice-with-the-query-store.md
  docs/relational-databases/performance/best-practice-with-the-query-store.md
Labels: Change sent to author, do-not-merge

#883 Modified trace flag 8207
  docs/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql.md
Labels: Change sent to author, do-not-merge

#898 Fixed FCI content
  docs/t-sql/functions/servername-transact-sql.md
Labels: Change sent to author, ready-to-merge

#892 Update columnstore-indexes-design-guidance.md
  docs/relational-databases/indexes/columnstore-indexes-design-guidance.md
Labels: Change sent to author, ready-to-merge

#895 Explain Listen All, multiple ports, and addresses
  docs/database-engine/configure-windows/configure-a-server-to-listen-on-a-specific-tcp-port.md
Labels: Change sent to author, ready-to-merge

#896 Added statement when MAX returns NULL
  docs/t-sql/functions/max-transact-sql.md
Labels: Change sent to author, ready-to-merge

#897 quotename-transact-sql.md - Acceptable single characters
  docs/t-sql/functions/quotename-transact-sql.md
Labels: Change sent to author, do-not-merge

#900 Update create-or-configure-an-availability-group-listener-sql-server.md
  docs/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server.md
Labels: Change sent to author, ready-to-merge

#899 gMSA Support
  docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md
Labels: Change sent to author, ready-to-merge

#901 Add information on configuring OpenSSL libraries
  docs/linux/sql-server-linux-encrypted-connections.md
Labels: Change sent to author, do-not-merge

#903 not supported in contained databases
  docs/relational-databases/track-changes/change-data-capture-and-other-sql-server-features.md
Labels: Change sent to author, ready-to-merge

#909 add missing identifiers
  docs/relational-databases/tutorial-ownership-chains-and-context-switching.md
Labels: Change sent to author, ready-to-merge

#906 fix toc levels and order
  docs/relational-databases/clr-integration-database-objects-user-defined-types/toc.yml
Labels: Change sent to author, ready-to-merge

#905 added missing space
  docs/relational-databases/clr-integration-database-objects-user-defined-types/clr-user-defined-types.md
Labels: Change sent to author, ready-to-merge

#904 remove token from heading
  docs/relational-databases/memory-management-architecture-guide.md
Labels: Change sent to author, ready-to-merge

#908 fix layout issues
  docs/relational-databases/security/authentication-access/principals-database-engine.md
Labels: Change sent to author, ready-to-merge

#910 add language to code snippet
  docs/relational-databases/system-functions/changetable-transact-sql.md
Labels: do-not-merge

#902 Update links
  docs/integration-services/security/access-control-for-sensitive-data-in-packages.md
Labels: Change sent to author, ready-to-merge

#907 Fix TOC level and order
  docs/relational-databases/clr-integration-data-access-transactions/toc.yml
Labels: Change sent to author, ready-to-merge

#912 Fix TOC level and order
  docs/relational-databases/clr-integration-database-objects-user-defined-functions/toc.yml
Labels: Change sent to author, ready-to-merge

#911 Update the index function running result
  docs/t-sql/functions/charindex-transact-sql.md
Labels: Change sent to author, ready-to-merge

#916 Update basic-availability-groups-always-on-availability-groups.md
  docs/database-engine/availability-groups/windows/basic-availability-groups-always-on-availability-groups.md
Labels: Change sent to author, ready-to-merge

#917 typo in Debian dependency command
  docs/sql-operations-studio/download.md
Labels: Change sent to author, ready-to-merge

#918 Updating mirror witness overview.
  docs/relational-databases/system-catalog-views/database-mirroring-witness-catalog-views-sys-database-mirroring-witnesses.md
Labels: Change sent to author, ready-to-merge

#919 Update alter-database-transact-sql.md
  docs/t-sql/statements/alter-database-transact-sql.md
Labels: do-not-merge

#924 Fix typo "Maser" - Update create-master-key-transact-sql.md
  docs/t-sql/statements/create-master-key-transact-sql.md
Labels: Change sent to author, ready-to-merge

#927 Update columnstore-indexes-overview.md
  docs/relational-databases/indexes/columnstore-indexes-overview.md
Labels: ready-to-merge

#928 Edit to correct typo "SYNCHONIZING"
  docs/database-engine/availability-groups/windows/some-synchronous-replicas-are-not-synchronized.md
Labels: Change sent to author, ready-to-merge

#914 Update sql-server-transaction-locking-and-row-versioning-guide.md
  docs/relational-databases/sql-server-transaction-locking-and-row-versioning-guide.md
Labels: Change sent to author, ready-to-merge

#923 CASE (Transact-SQL) Wording consistency
  docs/t-sql/language-elements/case-transact-sql.md
Labels: Change sent to author, ready-to-merge

#926 Correct copy and pasted query
  docs/relational-databases/backup-restore/disable-sql-server-managed-backup-to-microsoft-azure.md
Labels: Change sent to author, ready-to-merge

#931 Added example
  docs/t-sql/statements/restore-statements-verifyonly-transact-sql.md
Labels: Change sent to author, ready-to-merge

#929 typo
  docs/relational-databases/import-export/import-data-from-excel-to-sql.md
Labels: Change sent to author, ready-to-merge

#930 Update datediff-transact-sql.md
  docs/t-sql/functions/datediff-transact-sql.md
Labels: Change sent to author, ready-to-merge

#915 correct `size_based_cleanup_mode` code-to-desc
  docs/relational-databases/system-catalog-views/sys-database-query-store-options-transact-sql.md
Labels: Change sent to author, do-not-merge

#932 Small change sever to server
  docs/relational-databases/security/contained-database-users-making-your-database-portable.md
Labels: Change sent to author, ready-to-merge

#933 Update spn-registration-for-an-analysis-services-instance.md
  docs/analysis-services/instances/spn-registration-for-an-analysis-services-instance.md
Labels: Change sent to author, ready-to-merge

#934 IGNORE_DUP_KEY clarification
  docs/t-sql/statements/alter-table-index-option-transact-sql.md
Labels: Change sent to author, ready-to-merge

#938 Fix minor grammar issues
  docs/connect/ado-net/step-4-connect-resiliently-to-sql-with-ado-net.md
Labels: Change sent to author, ready-to-merge

#940 Update columnstore-indexes-described.md
  docs/2014/relational-databases/indexes/columnstore-indexes-described.md
Labels: Change sent to author, do-not-merge

#920 revise download language description
  docs/ssdt/download-sql-server-data-tools-ssdt.md
  docs/ssms/download-sql-server-management-studio-ssms.md
  docs/ssms/sql-server-management-studio-changelog-ssms.md
  docs/ssms/sql-server-management-studio-license-terms.md
Labels: Change sent to author, ready-to-merge

#944 Update rotate-always-encrypted-keys-using-powershell.md
  docs/relational-databases/security/encryption/rotate-always-encrypted-keys-using-powershell.md
Labels: Change sent to author, ready-to-merge

#943 Removed the three backticks in examples of column-expression section
  docs/t-sql/queries/select-group-by-transact-sql.md
Labels: Change sent to author, do-not-merge

#945 Fix Sample Output for Flat File connection
  docs/integration-services/building-packages-programmatically/adding-connections-programmatically.md
Labels: Change sent to author, ready-to-merge

#947 Fix typo in minor_id column description
  docs/relational-databases/system-catalog-views/sys-database-permissions-transact-sql.md
Labels: Change sent to author, ready-to-merge

#951 Update create-trigger-transact-sql.md
  docs/t-sql/statements/create-trigger-transact-sql.md
Labels: Change sent to author, ready-to-merge

#935 Update columnstore-indexes-overview.md
  docs/relational-databases/indexes/columnstore-indexes-overview.md
Labels: Change sent to author, ready-to-merge

#936 Secondary data files
  docs/linux/sql-server-linux-migrate-restore-database.md
Labels: Change sent to author, ready-to-merge

#952 typo
  docs/database-engine/configure-windows/open-the-odbc-data-source-administrator.md
Labels: Change sent to author, ready-to-merge

#953 Update columnstore-indexes-design-guidance.md
  docs/relational-databases/indexes/columnstore-indexes-design-guidance.md
Labels: Change sent to author, ready-to-merge
