Repository MicrosoftDocs/sql-docs, pull requests merged in 2018-09, with the labels that each got.

#950 Update create-an-entity-master-data-services.md
  docs/master-data-services/create-an-entity-master-data-services.md
Labels: Change sent to author, ready-to-merge

#954 change detault to default (spelling mistake)
  docs/sql-server/failover-clusters/windows/windows-server-failover-clustering-wsfc-with-sql-server.md
Labels: Change sent to author, ready-to-merge

#957 Update openrowset-transact-sql.md
  docs/t-sql/functions/openrowset-transact-sql.md
Labels: Change sent to author, do-not-merge, sql/prod

#960 Fix typos
  docs/ssms/sql-server-management-studio-changelog-ssms.md
Labels: Change sent to author, do-not-merge, sql/prod

#963 Fix wrong capital letter
  docs/advanced-analytics/tutorials/deepdive-data-science-deep-dive-using-the-revoscaler-packages.md
Labels: Change sent to author, ready-to-merge, sql/prod

#965 suggest to fix a link to the document of earlier versions
  docs/relational-databases/databases/model-database.md
Labels: Change sent to author, do-not-merge, sql/prod

#961 Update sp-create-plan-guide-transact-sql.md
  docs/relational-databases/system-stored-procedures/sp-create-plan-guide-transact-sql.md
Labels: Change sent to author, ready-to-merge, sql/prod

#958 Update sys-dm-db-index-physical-stats-transact-sql.md
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-index-physical-stats-transact-sql.md
Labels: Change sent to author, ready-to-merge, sql/prod

#949 Add file shrinks / growths info to FGCB_ADD_REMOVE
  docs/relational-databases/system-dynamic-management-views/sys-dm-os-latch-stats-transact-sql.md
Labels: Change sent to author, ready-to-merge

#964 Fix markdown error
  docs/advanced-analytics/tutorials/deepdive-work-with-sql-server-data-using-r.md
Labels: Change sent to author, ready-to-merge, sql/prod

#966 "Default Language" slightly off - Fixing couple of terms
  docs/database-engine/configure-windows/configure-the-default-language-server-configuration-option.md
Labels: Change sent to author, ready-to-merge, sql/prod

#967 Formatting on SORT_IN_TEMPDB option for indexes
  docs/relational-databases/indexes/sort-in-tempdb-option-for-indexes.md
Labels: Change sent to author, ready-to-merge, sql/prod

#969 Fixing typos and grammar
  docs/relational-databases/automatic-tuning/automatic-tuning.md
Labels: Change sent to author, do-not-merge, sql/prod

#973 adding a full name qualificaiton to the sp_setapprole infocation
  docs/relational-databases/system-stored-procedures/sp-setapprole-transact-sql.md
Labels: Change sent to author, ready-to-merge, sql/prod

#975 Fixed wording for better flow.
  docs/relational-databases/tables/changing-the-schema-of-a-system-versioned-temporal-table.md
Labels: Change sent to author, ready-to-merge, sql/prod

#942 Add Backup troubleshooting for VLDBs / 1117 I/O
  docs/relational-databases/backup-restore/sql-server-backup-to-url-best-practices-and-troubleshooting.md
Labels: Change sent to author, ready-to-merge, sql/prod

#977 Add space
  docs/advanced-analytics/tutorials/deepdive-query-and-modify-the-sql-server-data.md
Labels: Change sent to author, ready-to-merge, sql/prod

#978 Fixing number of Gen2 polybase readers
  docs/t-sql/statements/create-external-file-format-transact-sql.md
Labels: Change sent to author, ready-to-merge, sql/prod

#979 Update sql-server-backup-to-url.md
  docs/relational-databases/backup-restore/sql-server-backup-to-url.md
Labels: Change sent to author, ready-to-merge, sql/prod

#980 Change to capital letter
  docs/advanced-analytics/tutorials/deepdive-define-and-use-compute-contexts.md
Labels: Change sent to author, ready-to-merge, sql/prod

#982 Incorrect info for 2017 support
  docs/relational-databases/polybase/polybase-configuration.md
Labels: Change sent to author, ready-to-merge, sql/prod

#962 Update datediff-big-transact-sql.md
  docs/t-sql/functions/datediff-big-transact-sql.md
Labels: ready-to-merge

#972 Update configure-log-shipping-sql-server.md
  docs/database-engine/log-shipping/configure-log-shipping-sql-server.md
Labels: Change sent to author, ready-to-merge, sql/prod

#981 Added CLR data type limitation
  docs/relational-databases/indexes/create-filtered-indexes.md
Labels: ready-to-merge

#983 Fixing link to loading strategies blog post
  docs/t-sql/statements/create-external-file-format-transact-sql.md
Labels: Change sent to author, ready-to-merge, sql/prod

#989 Update ss-linux-cluster-pacemaker-create-login.md
  docs/includes/ss-linux-cluster-pacemaker-create-login.md
Labels: Change sent to author, do-not-merge

#991 Update replication-with-sql-database-managed-instance.md
  docs/relational-databases/replication/replication-with-sql-database-managed-instance.md
Labels: Change sent to author, ready-to-merge, sql/prod

#992 Revert "Update replication-with-sql-database-managed-instance.md"
  docs/relational-databases/replication/replication-with-sql-database-managed-instance.md
Labels: do-not-merge

#998 Change a link
  docs/linux/quickstart-install-connect-docker.md
Labels: Change sent to author, do-not-merge, sql/prod

#986 Update to reflect behavior seen in a case
  docs/tools/distributed-replay/configure-distributed-replay.md
Labels: Change sent to author, ready-to-merge, sql/prod

#987 small typo in the code of the XML format file
  docs/relational-databases/import-export/use-a-format-file-to-bulk-import-data-sql-server.md
Labels: Change sent to author, ready-to-merge, sql/prod

#970 Add See Also-links between LIKE and PATINDEX
  docs/t-sql/functions/patindex-transact-sql.md
  docs/t-sql/language-elements/like-transact-sql.md
Labels: Change sent to author, ready-to-merge, sql/prod

#993 Update claims-to-windows-token-service-c2wts-and-reporting-services.md
  docs/reporting-services/install-windows/claims-to-windows-token-service-c2wts-and-reporting-services.md
Labels: Change sent to author, ready-to-merge, reporting-services/prod

#984 Minor Text Fix
  docs/relational-databases/tables/rename-tables-database-engine.md
Labels: Change sent to author, do-not-merge, sql/prod

#996 Update what-s-new-in-sql-server-ver15.md
  docs/sql-server/what-s-new-in-sql-server-ver15.md
Labels: Change sent to author, ready-to-merge, sql-server-2018/prod

#988 fix stars
  docs/ssms/visual-db-tools/add-columns-to-queries-visual-database-tools.md
  docs/ssms/visual-db-tools/count-rows-in-a-table-visual-database-tools.md
  docs/ssms/visual-db-tools/create-insert-results-queries-visual-database-tools.md
  docs/ssms/visual-db-tools/create-make-table-queries-visual-database-tools.md
Labels: Change sent to author, do-not-merge, sql/prod

#971 Update export-a-data-tier-application.md
  docs/relational-databases/data-tier-applications/export-a-data-tier-application.md
Labels: Change sent to author, ready-to-merge, sql/prod

#1001 Fix folder and .EXE name
  docs/azure-data-studio/download.md
Labels: Change sent to author, do-not-merge, sql/prod

#995 Fix variable name
  docs/advanced-analytics/tutorials/deepdive-visualize-sql-server-data-using-r.md
Labels: Change sent to author, ready-to-merge, sql/prod

#1003 Update cluster-log-always-on-availability-groups.md
  docs/database-engine/availability-groups/windows/cluster-log-always-on-availability-groups.md
Labels: Change sent to author, ready-to-merge, sql/prod

#1000 Corrected grammar
  docs/t-sql/data-types/bit-transact-sql.md
Labels: Change sent to author, ready-to-merge, sql/prod

#1002 Fixing 'note' on page
  docs/advanced-analytics/r/sql-server-r-services-performance-tuning.md
Labels: Change sent to author, ready-to-merge, sql/prod

#1004 change a typo from "fron" to "from"
  docs/connect/jdbc/using-table-valued-parameters.md
Labels: Change sent to author, ready-to-merge, sql/prod

#1005 Correcting a minor typo on 2. Run `vs_setup.exe -NoWeb`
  docs/ssdt/download-sql-server-data-tools-ssdt.md
Labels: Change sent to author, do-not-merge, sql/prod

#1007 Update stgeometrytype-geography-data-type.md
  docs/t-sql/spatial-geography/stgeometrytype-geography-data-type.md
Labels: Change sent to author, ready-to-merge, sql/prod

#1011 Update export-a-data-tier-application.md
  docs/relational-databases/data-tier-applications/export-a-data-tier-application.md
Labels: Change sent to author, do-not-merge, sql/prod
