Repository MicrosoftDocs/sql-docs, pull requests merged in 2018-05, with the labels that each got.

#588 Update context-info-transact-sql.md
  docs/t-sql/functions/context-info-transact-sql.md
Labels: Change sent to author, do-not-merge

#589 Update conversion-functions-transact-sql.md
  docs/t-sql/functions/conversion-functions-transact-sql.md
Labels: Change sent to author, ready-to-merge

#590 Update cos-transact-sql.md
  docs/t-sql/functions/cos-transact-sql.md
Labels: Change sent to author, ready-to-merge

#591 Update cot-transact-sql.md
  docs/t-sql/functions/cot-transact-sql.md
Labels: Change sent to author, ready-to-merge

#593 Update count-transact-sql.md
  docs/t-sql/functions/count-transact-sql.md
Labels: Change sent to author, ready-to-merge

#594 Update cpu-busy-transact-sql.md
  docs/t-sql/functions/cpu-busy-transact-sql.md
Labels: Change sent to author, ready-to-merge

#601 Fixing wrong port on Quickstart.
  docs/linux/quickstart-install-connect-docker.md
Labels: Change sent to author, ready-to-merge

#592 Update count-big-transact-sql.md
  docs/t-sql/functions/count-big-transact-sql.md
Labels: Change sent to author, ready-to-merge

#596 Update crypt-gen-random-transact-sql.md
  docs/t-sql/functions/crypt-gen-random-transact-sql.md
Labels: Change sent to author, ready-to-merge

#597 Update cryptographic-functions-transact-sql.md
  docs/t-sql/functions/cryptographic-functions-transact-sql.md
Labels: Change sent to author, ready-to-merge

#602 Update cume-dist-transact-sql.md
  docs/t-sql/functions/cume-dist-transact-sql.md
Labels: Change sent to author, ready-to-merge

#603 Update current-request-id-transact-sql.md
  docs/t-sql/functions/current-request-id-transact-sql.md
Labels: Change sent to author, ready-to-merge

#583 ; doesn't work and fails on execution
  docs/advanced-analytics/tutorials/wrap-python-in-tsql-stored-procedure.md
Labels: Change sent to author, ready-to-merge

#599 Fix typo
  docs/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server.md
Labels: Change sent to author, ready-to-merge

#584 BLOB limit updates
  docs/relational-databases/backup-restore/sql-server-backup-to-url.md
Labels: Change sent to author, ready-to-merge

#604 Update download-sql-server-data-tools-ssdt.md
  docs/ssdt/download-sql-server-data-tools-ssdt.md
Labels: Change sent to author, ready-to-merge

#611 Update disable-foreign-key-constraints-with-insert-and-update-stateme…
  docs/relational-databases/tables/disable-foreign-key-constraints-with-insert-and-update-statements.md
Labels: ready-to-merge

#610 typo
  docs/relational-databases/system-functions/managed-backup-fn-backup-db-config-transact-sql.md
Labels: Change sent to author, ready-to-merge

#612 Update current-transaction-id-transact-sql.md
  docs/t-sql/functions/current-transaction-id-transact-sql.md
Labels: Change sent to author, ready-to-merge

#614 Update cursor-functions-transact-sql.md
  docs/t-sql/functions/cursor-functions-transact-sql.md
Labels: Change sent to author, ready-to-merge

#615 Update cursor-rows-transact-sql.md
  docs/t-sql/functions/cursor-rows-transact-sql.md
Labels: Change sent to author, ready-to-merge

#621 Update quickstart-install-connect-docker.md
  docs/linux/quickstart-install-connect-docker.md
Labels: Change sent to author, ready-to-merge

#609 Update current-timestamp-transact-sql.md
  docs/t-sql/functions/current-timestamp-transact-sql.md
Labels: Change sent to author, ready-to-merge

#608 Fixed missing `>` in alter database article
  docs/t-sql/statements/alter-database-azure-sql-database.md
Labels: Change sent to author, ready-to-merge, sql-database

#617 Update cursor-status-transact-sql.md
  docs/t-sql/functions/cursor-status-transact-sql.md
Labels: Change sent to author, ready-to-merge

#618 Update data-type-functions-transact-sql.md
  docs/t-sql/functions/data-type-functions-transact-sql.md
Labels: Change sent to author, ready-to-merge

#619 Update database-principal-id-transact-sql.md
  docs/t-sql/functions/database-principal-id-transact-sql.md
Labels: Change sent to author, ready-to-merge

#620 Update databaepropertyex-transact-sql.md
  docs/t-sql/functions/databasepropertyex-transact-sql.md
Labels: Change sent to author, ready-to-merge

#622 Update datalength-transact-sql.md
  docs/t-sql/functions/datalength-transact-sql.md
Labels: Change sent to author, ready-to-merge

#623 Typo in azure link
  docs/relational-databases/security/row-level-security.md
Labels: Change sent to author, ready-to-merge

#629 Removing inaccurate content
  docs/t-sql/statements/create-external-table-as-select-transact-sql.md
Labels: Change sent to author, ready-to-merge, sql-data-warehouse

#630 Seems the type is not right
  docs/t-sql/statements/create-external-data-source-transact-sql.md
Labels: Change sent to author, ready-to-merge

#632 Minor edit
  docs/reporting-services/report-server-sharepoint/powershell-cmdlets-for-reporting-services-sharepoint-mode.md
Labels: Change sent to author, ready-to-merge

#631 Update misleading statements about TRUNCATE TABLE
  docs/relational-databases/replication/administration/frequently-asked-questions-for-replication-administrators.md
Labels: Change sent to author, ready-to-merge

#606 Fixed incorrect definitions of JSON functions in json-data-sql-server.md
  docs/relational-databases/json/json-data-sql-server.md
Labels: Change sent to author, ready-to-merge

#635 Correct tiny typo
  docs/linux/sql-server-linux-migrate-bcp.md
Labels: Change sent to author, ready-to-merge

#636 remove wrong pointer dereference for 64-bit SQLSetXxx
  docs/odbc/reference/odbc-64-bit-information.md
Labels: Change sent to author, ready-to-merge

#607 Clarify the EMPTYFILE option
  docs/t-sql/database-console-commands/dbcc-shrinkfile-transact-sql.md
Labels: Change sent to author, do-not-merge

#637 fixed typo
  docs/includes/paragraph-content/get-help-options.md
Labels: Change sent to author, do-not-merge

#644 Update understanding-power-view-for-multidimensional-models.md
  docs/analysis-services/multidimensional-models/understanding-power-view-for-multidimensional-models.md
Labels: Change sent to author, ready-to-merge

#628 Added click the "Connect" button to enable the "Next"
  docs/integration-services/lift-shift/ssis-azure-deploy-run-monitor-tutorial.md
Labels: Change sent to author, do-not-merge

#646 Typo: MULTISUBMIT -> MULTISUBNET
  docs/relational-databases/native-client-odbc-api/sqlsetconnectattr.md
Labels: Change sent to author, ready-to-merge

#633 Update download-sql-server-management-studio-ssms.md
  docs/ssms/download-sql-server-management-studio-ssms.md
Labels: Change sent to author, do-not-merge

#605 Update dynamic-data-masking.md
  docs/relational-databases/security/dynamic-data-masking.md
Labels: Change sent to author, ready-to-merge

#616 added run_status=4 for In Progress
  docs/relational-databases/system-tables/dbo-sysjobhistory-transact-sql.md
Labels: ready-to-merge

#648 Fix missing space in error_level example
  docs/tools/sqlcmd-utility.md
Labels: Change sent to author, ready-to-merge

#649 Correcting typo in consistency check parameter name
  docs/relational-databases/tables/creating-a-system-versioned-temporal-table.md
Labels: Change sent to author, ready-to-merge

#651 Clarify default return value for property
  docs/t-sql/functions/databasepropertyex-transact-sql.md
Labels: Change sent to author, do-not-merge

#652 Update always-encrypted-cryptography.md
  docs/relational-databases/security/encryption/always-encrypted-cryptography.md
Labels: Change sent to author, ready-to-merge

#654 Incorrect result set column name
  docs/relational-databases/system-stored-procedures/sys-sp-cdc-get-captured-columns-transact-sql.md
Labels: Change sent to author, ready-to-merge

#656 Fix typo in datetimeoffset
  docs/t-sql/data-types/datetimeoffset-transact-sql.md
Labels: Change sent to author, ready-to-merge

#634 Update date-and-time-data-types-and-functions-transact-sql.md
  docs/t-sql/functions/date-and-time-data-types-and-functions-transact-sql.md
Labels: Change sent to author, ready-to-merge

#653 Update sys-dm-db-index-operational-stats-transact-sql.md
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-index-operational-stats-transact-sql.md
Labels: Change sent to author, ready-to-merge

#661 Update install-additional-r-packages-on-sql-server.md
  docs/advanced-analytics/r/install-additional-r-packages-on-sql-server.md
Labels: Change sent to author, ready-to-merge

#662 Update r-package-management-for-sql-server-r-services.md
  docs/advanced-analytics/r/r-package-management-for-sql-server-r-services.md
Labels: Change sent to author, ready-to-merge

#657 Corrected and clarified ANSI_NULLS remarks
  docs/t-sql/language-elements/comparison-operators-transact-sql.md
  docs/t-sql/language-elements/equals-transact-sql.md
Labels: Change sent to author, do-not-merge

#679 typo: Space in Markdown link to For Dummies link
  docs/advanced-analytics/r/r-and-data-optimization-r-services.md
Labels: Change sent to author, ready-to-merge

#681 typo: Missing "m" in RevoScalaR link
  docs/advanced-analytics/r/use-sqlbindr-exe-to-upgrade-an-instance-of-sql-server.md
Labels: Change sent to author, ready-to-merge

#682 typo: Spaces between Markdown link title and URL
  docs/advanced-analytics/r/install-pretrained-models-sql-server.md
Labels: Change sent to author, ready-to-merge

#683 typo: ttps -> https in URL
  docs/advanced-analytics/r/installing-sql-server-r-services-on-an-azure-virtual-machine.md
Labels: Change sent to author, ready-to-merge

#684 fix: Absolute to relative to sqlbinr link
  docs/advanced-analytics/known-issues-for-sql-server-machine-learning-services.md
Labels: Change sent to author, ready-to-merge

#685 fix: Absolute to relative URL for next walkthrough
  docs/advanced-analytics/tutorials/walkthrough-prepare-the-data.md
Labels: Change sent to author, ready-to-merge

#688 typo: mac -> macOS for developer getting started
  docs/connect/ado-net/microsoft-ado-net-for-sql-server.md
Labels: Change sent to author, ready-to-merge

#672 fix: Metadata and intenal MS staging link
  docs/relational-databases/tables/manage-retention-of-historical-data-in-system-versioned-temporal-tables.md
  docs/relational-databases/tables/system-versioned-temporal-tables-with-memory-optimized-tables.md
Labels: Change sent to author, ready-to-merge

#696 Update update-transact-sql.md
  docs/t-sql/queries/update-transact-sql.md
Labels: Change sent to author, ready-to-merge

#698 Underline "underline"
  docs/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql.md
Labels: Change sent to author, ready-to-merge

#700 Update add-transact-sql.md
  docs/t-sql/language-elements/add-transact-sql.md
Labels: Change sent to author, ready-to-merge

#658 add comparison table
  docs/t-sql/statements/set-ansi-nulls-transact-sql.md
Labels: Change sent to author, ready-to-merge

#659 Update xp-logevent-transact-sql.md
  docs/relational-databases/system-stored-procedures/xp-logevent-transact-sql.md
Labels: Change sent to author, ready-to-merge

#663 Update tempdb-database.md
  docs/relational-databases/databases/tempdb-database.md
Labels: Change sent to author, ready-to-merge

#665 Update dateadd-transact-sql.md
  docs/t-sql/functions/dateadd-transact-sql.md
Labels: Change sent to author, ready-to-merge

#666 Update tutorial-backup-restore-sql-server.md
  docs/sql-operations-studio/tutorial-backup-restore-sql-server.md
Labels: Change sent to author, ready-to-merge

#667 typo: Missing forward slash in URL
  docs/tools/sqlcmd-utility.md
Labels: Change sent to author, do-not-merge, ready-to-merge

#673 typo: Abosulute to relative link for always-on
  docs/relational-databases/databases/attach-a-database.md
Labels: Change sent to author, ready-to-merge

#674 typo: Abosolute to relative for rename-t-sql link
  docs/relational-databases/databases/rename-a-database.md
Labels: Change sent to author, ready-to-merge

#675 typo: new-sqlcolumnencryptionkeysettings has "key"
  docs/relational-databases/security/encryption/rotate-always-encrypted-keys-using-powershell.md
Labels: Change sent to author, ready-to-merge

#676 fix: Tutorial link to actual file
  docs/t-sql/statements/create-credential-transact-sql.md
Labels: Change sent to author, ready-to-merge

#689 Update datediff-big-transact-sql.md
  docs/t-sql/functions/datediff-big-transact-sql.md
Labels: Change sent to author, do-not-merge

#692 Fix [!IMPORTANT] note inside code block
  docs/t-sql/statements/create-index-transact-sql.md
Labels: Change sent to author, ready-to-merge

#693 Update statements.md
  docs/t-sql/statements/statements.md
Labels: Change sent to author, ready-to-merge

#694 Update alter-view-transact-sql.md
  docs/t-sql/statements/alter-view-transact-sql.md
Labels: Change sent to author, ready-to-merge

#697 Rearrange acceptable data types for accessibility
  docs/t-sql/functions/isnumeric-transact-sql.md
Labels: Change sent to author, ready-to-merge

#701 Update lesson-3-1-deleting-database-objects.md
  docs/t-sql/lesson-3-1-deleting-database-objects.md
Labels: Change sent to author, ready-to-merge

#699 Move "bit" under "numeric"
  docs/t-sql/data-types/TOC.md
Labels: Change sent to author, do-not-merge

#678 typo: Spaces in URL for AlwaysOn team blog
  docs/database-engine/availability-groups/windows/always-on-policies-for-operational-issues-always-on-availability.md
Labels: Change sent to author, do-not-merge

#647 Fix missing `)` in openjson-transact-sql.md
  docs/t-sql/functions/openjson-transact-sql.md
Labels: Change sent to author, do-not-merge

#668 typo: Markdown links with HTML escaped braces
  docs/analytics-platform-system/load-with-insert.md
  docs/analytics-platform-system/load-with-ssis.md
  docs/relational-databases/tutorial-sql-server-backup-and-restore-to-azure-blob-storage-service.md
  docs/reporting-services/subscriptions/manage-subscription-owners-and-run-subscription-powershell.md
Labels: Change sent to author, do-not-merge

#645 Update service-broker-with-always-on-availability-groups-sql-server.md
  docs/database-engine/availability-groups/windows/service-broker-with-always-on-availability-groups-sql-server.md
Labels: Change sent to author, ready-to-merge

#650 Add space after **ForceEncryption**.
  docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md
Labels: Change sent to author, ready-to-merge

#626 Update json-data-sql-server.md
  docs/relational-databases/json/json-data-sql-server.md
Labels: Change sent to author, do-not-merge

#664 Updates and fixes for disitributed availability groups
  docs/t-sql/statements/alter-availability-group-transact-sql.md
  docs/t-sql/statements/create-availability-group-transact-sql.md
Labels: Change sent to author, ready-to-merge

#686 typo: Absolute to relative link for next lesson
  docs/advanced-analytics/tutorials/walkthrough-prerequisites-for-data-science-walkthroughs.md
Labels: Change sent to author, do-not-merge

#669 typo: Trailing `.md` extension on `.aspx` link
  docs/analytics-platform-system/monitor-loads.md
Labels: Change sent to author, do-not-merge

#677 typo: Windows path used in URL
  docs/database-engine/availability-groups/windows/read-scale-availability-groups.md
Labels: Change sent to author, ready-to-merge

#687 fix: Absolute to relative for lesson links
  docs/advanced-analytics/tutorials/walkthrough-create-graphs-and-plots-using-r.md
Labels: ready-to-merge

#670 typo: docs/ssms/ in front of fully qualified url
  docs/ssms/new-updated-ssms.md
Labels: Change sent to author, do-not-merge

#702 Update use-the-availability-group-wizard-sql-server-management-studio.md
  docs/database-engine/availability-groups/windows/use-the-availability-group-wizard-sql-server-management-studio.md
Labels: Change sent to author, ready-to-merge

#704 Update from-transact-sql.md
  docs/t-sql/queries/from-transact-sql.md
Labels: Change sent to author, ready-to-merge

#703 typo: remove value from no value context SUSER_ID()
  docs/t-sql/functions/suser-sid-transact-sql.md
Labels: Change sent to author, do-not-merge

#691 Update sql-server-linux-db-mail-sql-agent.md
  docs/linux/sql-server-linux-db-mail-sql-agent.md
Labels: Change sent to author, do-not-merge

#695 Update delete-transact-sql.md
  docs/t-sql/statements/delete-transact-sql.md
Labels: Change sent to author, do-not-merge

#625 Update store-json-documents-in-sql-tables.md
  docs/relational-databases/json/store-json-documents-in-sql-tables.md
Labels: Change sent to author, do-not-merge
