Repository MicrosoftDocs/sql-docs, pull requests merged in 2018-07, with the labels that each got.

#830 Update match-sql-graph.md
  docs/t-sql/queries/match-sql-graph.md
Labels: Change sent to author, do-not-merge

#831 Update filegroup-name-transact-sql.md
  docs/t-sql/functions/filegroup-name-transact-sql.md
Labels: Change sent to author, do-not-merge

#834 Add STATISTICS_INCREMENTAL
  docs/t-sql/statements/create-table-transact-sql.md
Labels: Change sent to author, ready-to-merge

#768 Update eventdata-transact-sql.md
  docs/t-sql/functions/eventdata-transact-sql.md
Labels: Change sent to author, do-not-merge

#770 Update fetch-status-transact-sql.md
  docs/t-sql/functions/fetch-status-transact-sql.md
Labels: Change sent to author, do-not-merge

#774 Update filegroup-id-transact-sql.md
  docs/t-sql/functions/filegroup-id-transact-sql.md
Labels: Change sent to author, do-not-merge

#823 Fix typo rows -> row
  docs/t-sql/functions/rank-transact-sql.md
Labels: Change sent to author, do-not-merge

#773 Update file-name-transact-sql.md
  docs/t-sql/functions/file-name-transact-sql.md
Labels: Change sent to author, do-not-merge

#788 Decryption by Password definition
  docs/t-sql/statements/backup-certificate-transact-sql.md
Labels: Change sent to author, do-not-merge

#813 The option ERRORFILE_DATASOURCE is incorrect, it should be ERRORFILE_…
  docs/t-sql/statements/bulk-insert-transact-sql.md
Labels: Change sent to author, do-not-merge

#817 Remove the "constant" restriction
  docs/t-sql/functions/ntile-transact-sql.md
Labels: Change sent to author, do-not-merge

#820 remove duplicate sentence
  docs/t-sql/statements/restore-statements-rewindonly-transact-sql.md
Labels: Change sent to author, do-not-merge

#814 Increased clarity
  docs/relational-databases/tables/create-primary-keys.md
Labels: ready-to-merge

#833 Remove erroneous ':' in SQL date string
  docs/relational-databases/system-catalog-views/sys-event-log-azure-sql-database.md
Labels: Change sent to author, do-not-merge, sql-database

#825 Clarify the RECOMPILE option
  docs/t-sql/queries/hints-transact-sql-query.md
Labels: Change sent to author, do-not-merge

#744 Remote query timeout default seems wrong
  docs/database-engine/configure-windows/server-configuration-options-sql-server.md
Labels: Change sent to author, ready-to-merge

#818 Fix typo
  docs/relational-databases/indexes/enable-indexes-and-constraints.md
Labels: Change sent to author, ready-to-merge

#821 Add default for HeapTypeForObjects
  docs/analysis-services/server-properties/memory-properties.md
Labels: Change sent to author, ready-to-merge

#826 Typo in TSQL example
  docs/relational-databases/system-stored-procedures/xp-logevent-transact-sql.md
Labels: Change sent to author, do-not-merge

#835 Added an example of granting the CONTROL permission
  docs/t-sql/statements/grant-database-permissions-transact-sql.md
Labels: Change sent to author, ready-to-merge

#819 Update sql-server-linux-release-notes.md
  docs/linux/sql-server-linux-release-notes.md
Labels: Change sent to author, do-not-merge

#778 fix: Correct Topic links not pointing at files
  docs/integration-services/catalog/ssis-catalog.md
  docs/integration-services/system-stored-procedures/stored-procedures-integration-services-catalog.md
  docs/odbc/microsoft/supported-odbc-api-functions.md
Labels: Change sent to author, ready-to-merge

#836 Update sql-server-linux-availability-group-configure-rs.md
  docs/linux/sql-server-linux-availability-group-configure-rs.md
Labels: Change sent to author, ready-to-merge

#838 Update editions-and-components-of-sql-server-2017.md
  docs/sql-server/editions-and-components-of-sql-server-2017.md
Labels: Change sent to author, ready-to-merge

#840 Clarified the DROP statement
  docs/t-sql/statements/alter-table-transact-sql.md
Labels: Change sent to author, ready-to-merge

#841 Added cpu_limit column
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-resource-stats-azure-sql-database.md
Labels: Change sent to author, ready-to-merge, sql-database

#842 Removing odd sentence fragment
  docs/odbc/reference/structured-query-language-sql.md
Labels: Change sent to author, ready-to-merge

#845 Typo Fix
  docs/reporting-services/install-windows/troubleshoot-a-reporting-services-installation.md
Labels: Change sent to author, ready-to-merge

#844 Too many w's in the name.
  docs/samples/adventureworks-install-configure.md
Labels: Change sent to author, do-not-merge

#846 Fixed text on line 97
  docs/t-sql/functions/str-transact-sql.md
Labels: Change sent to author, ready-to-merge

#855 [CU9] SQL Server Agent is disabled if no conf entry
  docs/linux/sql-server-linux-configure-mssql-conf.md
Labels: Change sent to author, ready-to-merge

#848 Remove useless user and login
  docs/includes/ss-linux-cluster-availability-group-create-prereq.md
Labels: Change sent to author, do-not-merge

#847 Added cluster autostart command for Ubuntu pacemaker-based Availability Groups
  docs/linux/sql-server-linux-availability-group-cluster-ubuntu.md
Labels: Change sent to author, ready-to-merge

#854 ROLLBACK TRANSACTION: Corrected typo
  docs/t-sql/language-elements/rollback-transaction-transact-sql.md
Labels: Change sent to author, ready-to-merge

#849 Update backup-certificate-transact-sql.md
  docs/t-sql/statements/backup-certificate-transact-sql.md
Labels: Change sent to author, ready-to-merge

#852 Fixed missing semicolons in c# example code
  docs/reporting-services/report-server-web-service/net-framework/creating-the-web-service-proxy.md
Labels: Change sent to author, ready-to-merge

#851 Update sp-helppublication-transact-sql small mistype
  docs/relational-databases/system-stored-procedures/sp-helppublication-transact-sql.md
Labels: Change sent to author, ready-to-merge

#857 Author name & clarification
  docs/database-engine/availability-groups/windows/distributed-availability-groups.md
Labels: Change sent to author, do-not-merge

#858 Semicolons and GO added to syntax
  docs/database-engine/availability-groups/windows/distributed-availability-groups.md
Labels: Change sent to author, do-not-merge

#839 JSON path correction in example
  docs/relational-databases/json/json-data-sql-server.md
Labels: Change sent to author, ready-to-merge

#843 Typo Fix
  docs/reporting-services/lesson-3-defining-a-dataset-for-the-table-report-reporting-services.md
Labels: Change sent to author, ready-to-merge

#862 Update link to Volume Licensing
  docs/linux/sql-server-linux-configure-docker.md
Labels: Change sent to author, do-not-merge

#863 Update newid-transact-sql.md
  docs/t-sql/functions/newid-transact-sql.md
Labels: do-not-merge

#861 Formatting
  docs/relational-databases/track-changes/work-with-change-tracking-sql-server.md
Labels: Change sent to author, do-not-merge

#859 Fixed example code to use ANSI joins
  docs/database-engine/availability-groups/windows/distributed-availability-groups.md
Labels: Change sent to author, do-not-merge

#860 typo / grammar fixes
  docs/relational-databases/administer-multiple-servers-using-central-management-servers.md
Labels: Change sent to author, do-not-merge

#787 Refined Node.js -> PHP in PHP sentence.
  docs/connect/homepage-sql-connection-programming.md
Labels: Change sent to author, do-not-merge

#866 Simplified wording for WITH VALUES
  docs/t-sql/statements/alter-table-column-definition-transact-sql.md
  docs/t-sql/statements/alter-table-table-constraint-transact-sql.md
Labels: Change sent to author, ready-to-merge

#867 Fixed typos
  docs/relational-databases/system-dynamic-management-views/sys-dm-resource-governor-external-resource-pools.md
Labels: Change sent to author, ready-to-merge

#870 Removed no longer applicable note
  docs/relational-databases/system-dynamic-management-views/sys-dm-os-job-object-transact-sql.md
Labels: Change sent to author, ready-to-merge, sql-database

#874 Remove issues that appeared fixed but actually marked as duplicate
  docs/sql-operations-studio/release-notes.md
Labels: Change sent to author, ready-to-merge

#850 Added new example T for temp table creation.
  docs/t-sql/statements/create-table-transact-sql.md
Labels: Change sent to author, do-not-merge

#872 Update Label as a reserved keyword for SQL DW
  docs/t-sql/language-elements/reserved-keywords-transact-sql.md
Labels: Change sent to author, ready-to-merge

#875 Add new Standard and Premium tiers to service_objective
  docs/relational-databases/system-catalog-views/sys-database-service-objectives-azure-sql-database.md
Labels: Change sent to author, ready-to-merge, sql-database

#878 Add 236 = selective_xml_index_node_table
  docs/relational-databases/system-catalog-views/sys-internal-tables-transact-sql.md
Labels: Change sent to author, do-not-merge

#873 Update select-group-by-transact-sql.md
  docs/t-sql/queries/select-group-by-transact-sql.md
Labels: Change sent to author, do-not-merge

#832 Update filegroupproperty-transact-sql.md
  docs/t-sql/functions/filegroupproperty-transact-sql.md
Labels: Change sent to author, do-not-merge

#772 Update file-idex-transact-sql.md
  docs/t-sql/functions/file-idex-transact-sql.md
Labels: Change sent to author, do-not-merge

#877 Update monitoring-performance-by-using-the-query-store.md
  docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md
Labels: Change sent to author, ready-to-merge

#869 Update cast-and-convert-transact-sql.md
  docs/t-sql/functions/cast-and-convert-transact-sql.md
Labels: Change sent to author, ready-to-merge

#880 Fixed typo on Data Compression doc
  docs/relational-databases/data-compression/data-compression.md
Labels: Change sent to author, ready-to-merge

#881 Update lesson-5-automating-the-cleansing-and-matching-using-ssis.md
  docs/2014/tutorials/lesson-5-automating-the-cleansing-and-matching-using-ssis.md
Labels: Change sent to author, ready-to-merge

#879 Typo in UpdateAbility
  docs/database-engine/availability-groups/windows/configure-read-only-access-on-an-availability-replica-sql-server.md
Labels: Change sent to author, ready-to-merge

#884 Doc change for Expiry_date clause
  docs/t-sql/statements/create-certificate-transact-sql.md
Labels: Change sent to author, ready-to-merge

#888 Fix "bacup" typo
  docs/t-sql/statements/alter-table-transact-sql.md
Labels: Change sent to author, ready-to-merge
